In [21]:
#importing numpy package
import numpy as np


In [23]:
'''Task 1.
1. Write a function to compute 5/0 and use try/except to catch the exceptions.'''

#Function to compute 5/0
def division(): 
    
    #variables declaration
    a = 5
    b = 0
    #try block
    try:
        quotient = a/b
            
    #except block printing the exception message
    except ZeroDivisionError as e:
        print("Exception handled is: %s "%e)
        
    #else block printing the quotient value if denominator is not equal to 0
    else:
            print("Quotient value: %d "% quotient)
            

# function_call
division()

Exception handled is: division by zero 


In [4]:
'''2. Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].'''

#input lists
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

#function to generate sentences, returns list of generated sentences
def gen_sentence():
    
    output = [i+" "+j+" "+k for i in subjects for j in verbs for k in objects]
    return output
 

#function call
output_list = gen_sentence()
#prints the generated sentences
for i in output_list:
    print(i)


Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [16]:
'''Task 2:
   Write a function so that the columns of the output matrix are powers of the input vector.
   The order of the powers is determined by the increasing boolean argument. Specifically, when
   increasing is False, the i-th output column is the input vector raised element-wise to the power
   of N - i - 1.
'''

#Implementation using numpy's in-built vander() function
'''x- input array, 
   N -number of columns in output array, 
   increasing = boolean argument(True/False)'''

#input numpy array
x = np.array([1, 2, 3, 5])
N = 3

#function call with increasing argument = False
print(np.vander(x, N, False))

#function call with increasing argument = True
print(np.vander(x, N, True))


[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]]


In [17]:
#Own implementation of vander() using numpy
'''x- input array, 
   N -number of columns in output array,
   increasing = boolean argument(True/False)
   N and increasing values are taken from the user
    '''

#function accepts x-input array, N- number of columns in output, increasing - increasing boolean argument
def my_vander_funcn(x,N,increasing):
    
    if increasing ==  "True":
        output_array = np.column_stack([x**i for i in range(N)])
    else:
        output_array = np.column_stack([x**(N-1-i) for i in range(N)])

    return output_array


In [20]:
'''x- input array
   N- Number of columns in output(obtained from user)
      If N == 0, length of array is taken to be N
   increasing - increasing boolean argument -True/False(obtained from user)'''

x = np.array([1, 2, 3, 5])

N = int(input("Enter N value: "))
if(N == 0):
    N = len(x)
    
increasing = input("Enter increasing param value: ")
output_array = my_vander_funcn(x, N, increasing)
print(output_array)

Enter N value: 0
Enter increasing param value: False
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
